version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/docker-test
    ports:
      - "4000:4000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
