package shinzo.cineffi.domain.enums;

public enum Genre {
    ACTION, ADVENTURE, ANIMATION, COMEDY,
    CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY,
    HISTORY, HORROR, MUSIC, MYSTERY, ROMANCE,
    SCIENCE_FICTION, TV_MOVIE, THRILLER, WAR, WESTERN
}